In [1]:
using GameTheory
using Polyhedra
using CDDLib

In [2]:
player1 = Player([3 3; 2 5; 0 6])
player2 = Player([3 2 3; 2 6 1])
g = NormalFormGame(player1, player2)
println(g)

3×2 NormalFormGame{2, Int64}:
 [3, 3]  [3, 2]
 [2, 2]  [5, 6]
 [0, 3]  [6, 1]


In [3]:
n, m = size(player1.payoff_array)

(3, 2)

In [4]:
B = player1.payoff_array

3×2 Matrix{Int64}:
 3  3
 2  5
 0  6

In [5]:
function best_response_polytope(opponent_player::Player{2}, idx::Integer)
    B = opponent_player.payoff_array
    (n, m) = size(B)
    D = zeros(m+n, m)
    
    (nonneg_cond_start, payoff_cond_start) = idx == 1 ? (0, m) : (n, 0)
    
    D[payoff_cond_start+1:payoff_cond_start+n, :] = B
    for i in 1:m
        D[nonneg_cond_start+i, i] = -1
    end
    
    # Shift the payoffs to be positive (bounded away from zero)
    min_ = minimum(B)
    if min_ < 1
        D[payoff_cond_start+1:payoff_cond_start+n, :] .+= (-min_ + 1)
    end
    
    D
end

best_response_polytope (generic function with 1 method)

In [6]:
best_response_polytope(player2, 2)

5×3 Matrix{Float64}:
  3.0   2.0   3.0
  2.0   6.0   1.0
 -1.0   0.0   0.0
  0.0  -1.0   0.0
  0.0   0.0  -1.0

In [7]:
best_response_polytope(player1, 1)

5×2 Matrix{Float64}:
 -1.0   0.0
  0.0  -1.0
  4.0   4.0
  3.0   6.0
  1.0   7.0